#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    ar=arr[n-1]
    c=1
    for i in range(n-2,-1,-1):
        if(ar>arr[i]):
            arr[n-c]=ar
            print(" ".join(str(x) for x in arr))
            return
        else:
            arr[n-c]=arr[i]
            c+=1
            print(" ".join(str(x) for x in arr))
    arr[0]=ar        
    print(" ".join(str(x) for x in arr))    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
